theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag
  
image: "FacebookLogo.png"

description: "Use FTAnalyzer to investigate your family tree in new and interesting ways. Find errors in your tree eg: childrens birthdates before parent was born. See lists of who is missing from census searches then click their name to automatically search on Ancestry, Find My Past, Familysearch etc. And lots more."

defaults: 
  - 
    scope: 
      path: "" 
    values: 
      image: "FacebookLogo.png"
      author: "Alexander Bisset"
      
social:
    name: Family Tree Analyzer
    links:
      - https://www.facebook.com/ftanalyzer
      - https://twitter.com/ftanalyzer
      
twitter:
  username: ftanalyzer

description: "Use FTAnalyzer to investigate your family tree in new and interesting ways. Find errors in your tree eg: childrens birthdates before parent was born. See lists of who is missing from census searches then click their name to automatically search on Ancestry, Find My Past, Familysearch etc. And lots more."
